chromadb_path: "/Users/ipsitapanda/database_data_validation/chromadb"
chunk_overlap: 50
chunk_size: 500
data_directory: "/Users/ipsitapanda/database_data_validation/data_validation"
embedding_model: nomic-embed-text
ge_dir: ./great_expectations
# Schemas to compare
schemas:
  - schema_one_50plus
  - schema_two_50plus
source-schema: schema_one_50plus
dest-schema: schema_two_50plus
schema_paths:
  schema_one_50plus: "/Users/ipsitapanda/database_data_validation/uploads/source/schema_one_50plus"
  schema_two_50plus: "/Users/ipsitapanda/database_data_validation/uploads/destination/schema_two_50plus"