chromadb_path: ./chromadb
chunk_overlap: 50
chunk_size: 500
data_directory: ./data_validation/
embedding_model: nomic-embed-text
ge_dir: ./great_expectations
# Schemas to compare
schemas:
  - employee_management
  - contractor_management